---
- name: install haproxy and socat
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - haproxy
    - socat

- name: create /etc/default/haproxy
  file:
    path: /etc/default/haproxy
    owner: root
    group: root
    mode: 0644
    state: touch

- name: enable haproxy
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED"
    line: "ENABLED=1"
  notify: restart haproxy

- name: deploy haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
